Resources:
  Trail:
    Type: AWS::CloudTrail::Trail
    Properties:
      S3BucketName: !Ref BucketName
      S3KeyPrefix: "Uluru"
      IsLogging: true
      TrailName: !Ref TrailName
      EnableLogFileValidation: false
      IncludeGlobalServiceEvents: true
      IsMultiRegionTrail: false
      CloudWatchLogsLogGroupArn:
        Fn::ImportValue: "TrailLogGroupTestArn"
      CloudWatchLogsRoleArn:
        Fn::ImportValue: "TrailLogGroupRoleTestArn"
      KMSKeyId:
        Fn::ImportValue: TrailKeyTest
      Tags:
        - Key: "TagKeyIntTest"
          Value: "TagValueIntTest"
        - Key: "TagKeyIntTest2"
          Value: "TagValueIntTest2"
      SnsTopicName:
        Fn::ImportValue: TrailTopicTest
      EventSelectors:
        - DataResources:
            - Type: AWS::S3::Object
              Values:
                - !Sub "arn:${AWS::Partition}:s3:::"
          IncludeManagementEvents: true
          ReadWriteType: All
Outputs:
  ARN:
    Description: The trail ARN
    Value:
      'Fn::GetAtt':
        - Trail
        - Arn
  TopicArn:
    Description: The SnS Topic ARN
    Value:
      'Fn::GetAtt':
        - Trail
        - SnsTopicArn
